# Generated by Django 3.0.5 on 2024-12-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_auto_20241216_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='patientId',
            field=models.IntegerField(unique=True),
        ),
    ]
