# Generated by Django 3.0.5 on 2024-12-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0021_auto_20241216_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='releaseDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
